#!/bin/sh
# Home Cleanup

# Define XDG homes
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export DOTFILES_HOME="$HOME/Documentos/dotfiles/"

# Export path for programs 
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export LESSHISTFILE="-"
export HISTFILE="$XDG_STATE_HOME/shell/history"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export CUPS_DATADIR="$XDG_DATA_HOME/cups"
export W3M_DIR="$XDG_DATA_HOME/w3m"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export KERAS_HOME="${XDG_STATE_HOME}/keras"
export GOPATH="${XDG_DATA_HOME}/go"
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export MPDCONF="$XDG_CONFIG_HOME/mpd/mpd.conf"
