return {
	-- "zbirenbaum/copilot.lua",
	-- cmd = "Copilot",
	-- event = "InsertEnter",
	-- opts = {
	-- 	suggestion = {
	-- 		enable = true,
	-- 		auto_trigger = true,
	-- 		debounce = 75,
	-- 		keymap = {
	-- 			accept = "<M-l>",
	-- 		},
	-- 	},
	-- 	filetypes = {
	-- 		yaml = false,
	-- 		markdown = false,
	-- 		help = false,
	-- 		gitcommit = false,
	-- 		gitrebase = false,
	-- 		hgcommit = false,
	-- 		svn = false,
	-- 		cvs = false,
	-- 		go = false,
	-- 		["."] = false,
	-- 	},
	-- 	copilot_node_command = "node", -- Node.js version must be > 18.x
	-- 	server_opts_overrides = {},
	-- },
}
